import type { Metadata } from "next";
import Link from "next/link";
import { MessageCircleHeart, ScanSearch, ShieldAlert, Lock, AlertTriangle } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { Card } from "@/components/ui/Card";
import { ScreenshotFrame } from "@/components/ui/ScreenshotFrame";
import { Reveal, RevealGroup } from "@/components/motion/Reveal";
import { dhruvAiFeature } from "@/lib/content/features";
import { aiDisclaimerBody } from "@/lib/content/legal";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({
  title: "Dhruv AI",
  description:
    "Meet Dhruv AI, MaaSphere's AI-powered pregnancy companion — how it works, its built-in safety checks, and its limits.",
  path: "/dhruv-ai",
});

const howItWorks = [
  {
    icon: MessageCircleHeart,
    title: "You ask, in plain language",
    body: "Ask about symptoms, nutrition, baby development, or anything else on your mind — no rigid menus, just a normal conversation.",
  },
  {
    icon: ScanSearch,
    title: "It reads your own logged context",
    body: "Your current pregnancy week, recent symptoms, and other data you've already logged in MaaSphere inform the response — so answers are personal, not generic.",
  },
  {
    icon: ShieldAlert,
    title: "Built-in safety checks run first",
    body: "Both what you type and your recent logged data are scanned for signs of a possible emergency before any answer is generated.",
  },
  {
    icon: Lock,
    title: "A safeguarded response comes back",
    body: "Every answer is generated by Claude (Anthropic) through MaaSphere's own backend, and carries a built-in reminder that it's informational, not a diagnosis.",
  },
];

export default function DhruvAiPage() {
  return (
    <div className="bg-background">
      <section className="bg-hero-gradient py-20 sm:py-28">
        <Container className="grid items-center gap-14 lg:grid-cols-2 lg:gap-20">
          <Reveal>
            <span className="text-[12px] font-semibold uppercase tracking-[0.14em] text-warmth-gold">
              Dhruv AI
            </span>
            <h1 className="mt-5 text-balance text-[38px] font-semibold leading-[1.15] tracking-[-0.02em] text-warmth-cream sm:text-[48px]">
              A calm, knowledgeable companion — never a replacement for your doctor
            </h1>
            <p className="mt-5 max-w-[520px] text-balance text-[17px] leading-relaxed text-warmth-cream/75">
              {dhruvAiFeature.tagline} Dhruv AI answers everyday questions and points you toward
              your care team the moment something needs one.
            </p>
          </Reveal>
          <Reveal delay={0.1} className="mx-auto w-[240px] sm:w-[280px]">
            <ScreenshotFrame
              filename={dhruvAiFeature.screenshot}
              alt={dhruvAiFeature.screenshotAlt}
              accent="gold"
              priority
            />
          </Reveal>
        </Container>
      </section>

      <section className="py-24 sm:py-28">
        <Container>
          <SectionHeading
            eyebrow="How it works"
            title="Four steps behind every response"
            className="mb-14"
          />
          <RevealGroup className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {howItWorks.map((step, index) => (
              <Reveal key={step.title}>
                <Card className="h-full">
                  <span className="text-[13px] font-semibold text-warmth-gold-deep">
                    Step {index + 1}
                  </span>
                  <step.icon className="mt-3 text-ink" size={24} aria-hidden="true" />
                  <h3 className="mt-3 text-[16px] font-semibold text-ink">{step.title}</h3>
                  <p className="mt-2 text-[14px] leading-relaxed text-text-secondary">
                    {step.body}
                  </p>
                </Card>
              </Reveal>
            ))}
          </RevealGroup>
        </Container>
      </section>

      <section className="bg-surface-muted py-24 sm:py-28">
        <Container className="max-w-[760px]">
          <SectionHeading
            eyebrow="Safety first"
            title="What Dhruv AI is honest about"
            className="mb-10"
          />
          <Reveal>
            <Card className="border border-warmth-gold-deep/30 bg-surface">
              <div className="flex gap-3">
                <AlertTriangle className="mt-0.5 shrink-0 text-error" size={20} aria-hidden="true" />
                <p className="text-[15px] leading-relaxed text-text-primary">
                  Dhruv AI&rsquo;s built-in safety checks can flag a possible emergency and route you to
                  guidance — but they are a helpful layer, not a clinical safety system. If you
                  believe you or your baby may be experiencing a medical emergency, call your local
                  emergency number immediately. Never wait on a response from the app.
                </p>
              </div>
            </Card>
          </Reveal>
          <Reveal delay={0.08}>
            <ul className="mt-8 flex flex-col gap-4">
              {dhruvAiFeature.bullets.map((bullet) => (
                <li key={bullet} className="flex gap-3 text-[15px] leading-relaxed text-text-primary">
                  <span className="mt-[9px] h-1.5 w-1.5 shrink-0 rounded-full bg-warmth-gold-deep" />
                  <span>{bullet}</span>
                </li>
              ))}
            </ul>
          </Reveal>
        </Container>
      </section>

      <section className="py-24 sm:py-28">
        <Container className="max-w-[760px]">
          <SectionHeading eyebrow="Privacy" title="What happens to your conversation" className="mb-10" />
          <Reveal>
            <p className="text-[16px] leading-relaxed text-text-secondary">
              Your messages to Dhruv AI, and the pregnancy/health context needed to answer them,
              are processed by Anthropic to generate a response, and your conversation is stored
              so you can return to it later. Conversations may be reviewed in aggregate or
              anonymized form to improve the safety and quality of the assistant. See our{" "}
              <Link href="/legal/privacy-policy" className="font-semibold text-ink underline underline-offset-4">
                Privacy Policy
              </Link>{" "}
              for the full detail on how this data is handled, retained, and protected.
            </p>
          </Reveal>
        </Container>
      </section>

      <section className="bg-surface-muted py-24 sm:py-28">
        <Container className="max-w-[760px]">
          <SectionHeading eyebrow="AI Disclaimer" title="The exact disclaimer shown in-app" className="mb-10" />
          <Reveal>
            <Card className="whitespace-pre-line text-[15px] leading-[1.75] text-text-primary">
              {aiDisclaimerBody}
            </Card>
          </Reveal>
          <p className="mt-6 text-center text-[14px] text-text-secondary">
            Read the full{" "}
            <Link href="/legal/ai-disclaimer" className="font-semibold text-ink underline underline-offset-4">
              AI Disclaimer
            </Link>{" "}
            and{" "}
            <Link href="/legal/medical-disclaimer" className="font-semibold text-ink underline underline-offset-4">
              Medical Disclaimer
            </Link>
            .
          </p>
        </Container>
      </section>
    </div>
  );
}
